
import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Tag, Database, CheckCircle, XCircle, Users, RefreshCw, UserPlus, Building } from 'lucide-react';
import { AppSettings, DatabaseConfig, User } from '../types';

interface SettingsProps {
  settings: AppSettings;
  onUpdateSettings: (newSettings: AppSettings) => void;
  authToken: string | null;
}

const Settings: React.FC<SettingsProps> = ({ settings, onUpdateSettings, authToken }) => {
  const [activeTab, setActiveTab] = useState<'GENERAL' | 'DATABASE' | 'USERS' | 'COMPANIES'>('GENERAL');
  
  // Local state
  const [newCategory, setNewCategory] = useState('');
  const [newCompany, setNewCompany] = useState('');
  const [dbConfig, setDbConfig] = useState<DatabaseConfig>(settings.database);
  
  // User Management State
  const [users, setUsers] = useState<User[]>([]);
  const [newUsername, setNewUsername] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [userLoading, setUserLoading] = useState(false);
  const [categoryLoading, setCategoryLoading] = useState(false);
  const [companyLoading, setCompanyLoading] = useState(false);
  
  const [isTestingDB, setIsTestingDB] = useState(false);
  const [dbMessage, setDbMessage] = useState<{type: 'success' | 'error', text: string} | null>(null);

  useEffect(() => {
    // Fetch users when tab becomes active
    if (activeTab === 'USERS' && authToken) {
        fetchUsers();
    }
  }, [activeTab, authToken]);

  const fetchUsers = async () => {
      if (!authToken) return;
      try {
          const res = await fetch('/api/users', {
            headers: { 'Authorization': `Bearer ${authToken}` }
          });
          const data = await res.json();
          if (Array.isArray(data)) setUsers(data);
      } catch (e) {
          console.error("Failed to fetch users");
      }
  }

  // --- Category Handlers ---
  const handleAddCategory = async (e: React.FormEvent) => {
    e.preventDefault();
    const catName = newCategory.trim();
    if (!catName || settings.categories.includes(catName)) return;

    if (authToken) {
       setCategoryLoading(true);
       try {
          const res = await fetch('/api/categories', {
              method: 'POST',
              headers: { 
                 'Content-Type': 'application/json',
                 'Authorization': `Bearer ${authToken}` 
              },
              body: JSON.stringify({ name: catName })
          });
          const data = await res.json();
          if (!data.success) {
             alert(data.message || 'Gagal menambahkan kategori ke server');
             setCategoryLoading(false);
             return;
          }
       } catch (err) {
          alert('Gagal menghubungi server');
          setCategoryLoading(false);
          return;
       }
       setCategoryLoading(false);
    }

    // Update local state immediately after success
    onUpdateSettings({
      ...settings,
      categories: [...settings.categories, catName]
    });
    setNewCategory('');
  };

  const handleDeleteCategory = async (cat: string) => {
    if (!confirm(`Hapus kategori "${cat}"?`)) return;

    if (authToken) {
        try {
            const res = await fetch(`/api/categories/${encodeURIComponent(cat)}`, {
                method: 'DELETE',
                headers: { 'Authorization': `Bearer ${authToken}` }
            });
            const data = await res.json();
            if (!data.success) {
                alert("Gagal menghapus kategori di server");
                return;
            }
        } catch (e) {
            alert("Gagal menghubungi server");
            return;
        }
    }

    onUpdateSettings({
      ...settings,
      categories: settings.categories.filter(c => c !== cat)
    });
  };

  // --- Company Handlers ---
  const handleAddCompany = async (e: React.FormEvent) => {
    e.preventDefault();
    const compName = newCompany.trim();
    if (!compName || settings.companies.some(c => c.name === compName)) return;

    if (authToken) {
       setCompanyLoading(true);
       try {
          const res = await fetch('/api/companies', {
              method: 'POST',
              headers: { 
                 'Content-Type': 'application/json',
                 'Authorization': `Bearer ${authToken}` 
              },
              body: JSON.stringify({ name: compName })
          });
          const data = await res.json();
          if (!data.success) {
             alert(data.message || 'Gagal menambahkan perusahaan ke server');
             setCompanyLoading(false);
             return;
          }
       } catch (err) {
          alert('Gagal menghubungi server');
          setCompanyLoading(false);
          return;
       }
       setCompanyLoading(false);
    }

    // Refresh settings (in real app we might want to re-fetch, but here we can just add it if we had the ID, 
    // but since ID is generated by DB, we better re-fetch or mock ID for now. 
    // Ideally, App.tsx should handle re-fetching or we return the new object from API.
    // For now, let's assume we refresh the whole app or just add it locally with a temp ID if not critical, 
    // but since ID is needed for foreign keys, we MUST get the ID from server.
    // The API returns success message but not the object. I should update API to return the object or ID.
    // But I can also just re-fetch companies.
    
    // Better approach: Trigger a re-fetch in App.tsx? 
    // Or just update local state with a temp ID and hope user refreshes? 
    // No, I'll update the API to return the ID or just re-fetch here if I could.
    // But onUpdateSettings expects the full object.
    
    // Let's rely on the user refreshing or subsequent fetches. 
    // Wait, if I add it, I want to see it.
    // I will trigger a re-fetch of settings if possible.
    // But here I only have onUpdateSettings.
    // I'll make a quick fetch to get the latest list.
    if (authToken) {
        const res = await fetch('/api/companies', { headers: { 'Authorization': `Bearer ${authToken}` } });
        const data = await res.json();
        if (Array.isArray(data)) {
            onUpdateSettings({ ...settings, companies: data });
        }
    }
    setNewCompany('');
  };

  const handleDeleteCompany = async (id: number) => {
    if (!confirm(`Hapus perusahaan ini?`)) return;

    if (authToken) {
        try {
            const res = await fetch(`/api/companies/${id}`, {
                method: 'DELETE',
                headers: { 'Authorization': `Bearer ${authToken}` }
            });
            const data = await res.json();
            if (!data.success) {
                alert("Gagal menghapus perusahaan di server");
                return;
            }
        } catch (e) {
            alert("Gagal menghubungi server");
            return;
        }
    }

    onUpdateSettings({
      ...settings,
      companies: settings.companies.filter(c => c.id !== id)
    });
  };

  // --- User Handlers ---
  const handleAddUser = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!newUsername.trim() || !newPassword.trim()) return;
      if (!authToken) return alert("Sesi habis");

      setUserLoading(true);
      try {
          const res = await fetch('/api/users', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${authToken}`
              },
              body: JSON.stringify({ username: newUsername, password: newPassword })
          });
          const data = await res.json();
          if (data.success) {
              setNewUsername('');
              setNewPassword('');
              fetchUsers();
              alert("User berhasil dibuat!");
          } else {
              alert(data.message);
          }
      } catch (e) {
          alert("Gagal membuat user");
      } finally {
          setUserLoading(false);
      }
  };

  const handleDeleteUser = async (id: number) => {
      if(!confirm("Yakin ingin menghapus user ini?")) return;
      if (!authToken) return alert("Sesi habis");
      try {
          const res = await fetch(`/api/users/${id}`, { 
            method: 'DELETE',
            headers: { 'Authorization': `Bearer ${authToken}` }
          });
          const data = await res.json();
          if(data.success) fetchUsers();
      } catch(e) {
          alert("Gagal hapus user");
      }
  };

  // --- Database Handlers ---
  const testDbConnection = async () => {
    setIsTestingDB(true);
    setDbMessage(null);
    try {
      // Test DB route is public, but we can secure it if needed. Leaving public for diagnostics.
      const response = await fetch('/api/test-db');
      const data = await response.json();
      if (data.status === 'success') {
        setDbConfig(prev => ({ ...prev, isConnected: true }));
        setDbMessage({ type: 'success', text: data.message });
        onUpdateSettings({ ...settings, database: { ...dbConfig, isConnected: true } });
      } else {
        throw new Error(data.message);
      }
    } catch (error: any) {
      setDbMessage({ type: 'error', text: error.message || 'Gagal terkoneksi ke server.' });
    } finally {
      setIsTestingDB(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <h2 className="text-2xl font-bold text-slate-800">Pengaturan Aplikasi</h2>

      {/* TABS */}
      <div className="flex space-x-1 bg-slate-100 p-1 rounded-xl w-fit overflow-x-auto">
        <button
          onClick={() => setActiveTab('GENERAL')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'GENERAL' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          Kategori
        </button>
        <button
          onClick={() => setActiveTab('COMPANIES')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'COMPANIES' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          Perusahaan
        </button>
        <button
          onClick={() => setActiveTab('USERS')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'USERS' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          Manajemen User
        </button>
        <button
          onClick={() => setActiveTab('DATABASE')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'DATABASE' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          Database
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* CONTENT AREA */}
        <div className="md:col-span-2 space-y-6">
          
          {/* --- GENERAL TAB --- */}
          {activeTab === 'GENERAL' && (
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                  <Tag size={20} />
                </div>
                <div>
                   <h3 className="text-lg font-bold text-slate-800">Kategori Kegiatan</h3>
                   <p className="text-xs text-slate-500">Kelola kategori untuk dropdown input.</p>
                </div>
              </div>

              <form onSubmit={handleAddCategory} className="flex gap-2 mb-6">
                <input 
                  type="text" 
                  placeholder="Nama Kategori Baru..." 
                  value={newCategory}
                  onChange={(e) => setNewCategory(e.target.value)}
                  className="flex-1 rounded-lg border-slate-300 bg-slate-50 text-slate-900 border p-2.5 focus:ring-2 focus:ring-blue-500 outline-none"
                  disabled={categoryLoading}
                />
                <button 
                  type="submit"
                  disabled={!newCategory.trim() || categoryLoading}
                  className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors font-medium"
                >
                  {categoryLoading ? <RefreshCw size={18} className="animate-spin" /> : <Plus size={18} />} Tambah
                </button>
              </form>

              <div className="space-y-2 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                {settings.categories.map((cat, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100 group hover:border-blue-200 transition-colors">
                    <span className="text-slate-700 font-medium">{cat}</span>
                    <button onClick={() => handleDeleteCategory(cat)} className="text-slate-400 hover:text-rose-500 p-1"><Trash2 size={16} /></button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* --- COMPANIES TAB --- */}
          {activeTab === 'COMPANIES' && (
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
              <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                  <Building size={20} />
                </div>
                <div>
                   <h3 className="text-lg font-bold text-slate-800">Manajemen Perusahaan</h3>
                   <p className="text-xs text-slate-500">Kelola daftar perusahaan (PT) untuk transaksi.</p>
                </div>
              </div>

              <form onSubmit={handleAddCompany} className="flex gap-2 mb-6">
                <input 
                  type="text" 
                  placeholder="Nama PT Baru..." 
                  value={newCompany}
                  onChange={(e) => setNewCompany(e.target.value)}
                  className="flex-1 rounded-lg border-slate-300 bg-slate-50 text-slate-900 border p-2.5 focus:ring-2 focus:ring-blue-500 outline-none"
                  disabled={companyLoading}
                />
                <button 
                  type="submit"
                  disabled={!newCompany.trim() || companyLoading}
                  className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors font-medium"
                >
                  {companyLoading ? <RefreshCw size={18} className="animate-spin" /> : <Plus size={18} />} Tambah
                </button>
              </form>

              <div className="space-y-2 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                {settings.companies && settings.companies.map((comp) => (
                  <div key={comp.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100 group hover:border-blue-200 transition-colors">
                    <span className="text-slate-700 font-medium">{comp.name}</span>
                    <button onClick={() => handleDeleteCompany(comp.id)} className="text-slate-400 hover:text-rose-500 p-1"><Trash2 size={16} /></button>
                  </div>
                ))}
                {(!settings.companies || settings.companies.length === 0) && (
                    <div className="text-center p-4 text-slate-400 text-sm">Belum ada data perusahaan.</div>
                )}
              </div>
            </div>
          )}

          {/* --- USER MANAGEMENT TAB --- */}
          {activeTab === 'USERS' && (
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                <div className="flex items-center gap-3 mb-6">
                    <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                        <Users size={20} />
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-slate-800">Manajemen User</h3>
                        <p className="text-xs text-slate-500">Tambah atau hapus akses pengguna sistem.</p>
                    </div>
                </div>

                <form onSubmit={handleAddUser} className="bg-slate-50 p-4 rounded-lg border border-slate-200 mb-6">
                    <h4 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2"><UserPlus size={16}/> Tambah User Baru</h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                        <input type="text" placeholder="Username" required value={newUsername} onChange={e => setNewUsername(e.target.value)} className="p-2 rounded border border-slate-300 text-sm" />
                        <input type="password" placeholder="Password" required value={newPassword} onChange={e => setNewPassword(e.target.value)} className="p-2 rounded border border-slate-300 text-sm" />
                    </div>
                    <button disabled={userLoading} className="w-full bg-blue-600 text-white py-2 rounded text-sm font-medium hover:bg-blue-700 transition">
                        {userLoading ? 'Memproses...' : 'Buat User'}
                    </button>
                </form>

                <div className="overflow-hidden border border-slate-200 rounded-lg">
                    <table className="w-full text-left text-sm">
                        <thead className="bg-slate-100 text-slate-600 font-semibold">
                            <tr>
                                <th className="p-3">Username</th>
                                <th className="p-3">Role</th>
                                <th className="p-3 text-right">Aksi</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {users.map((u, index) => (
                                <tr key={u.id} className="even:bg-slate-50">
                                    <td className="p-3 text-slate-800">{u.username}</td>
                                    <td className="p-3 text-slate-500 uppercase text-xs font-bold">{u.role}</td>
                                    <td className="p-3 text-right">
                                        <button onClick={() => handleDeleteUser(u.id)} className="text-rose-500 hover:text-rose-700 p-1"><Trash2 size={16}/></button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
          )}

          {/* --- DATABASE TAB --- */}
          {activeTab === 'DATABASE' && (
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
               <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-indigo-100 rounded-lg text-indigo-600">
                  <Database size={20} />
                </div>
                <div>
                   <h3 className="text-lg font-bold text-slate-800">Koneksi MySQL</h3>
                   <p className="text-xs text-slate-500">Konfigurasi database server.</p>
                </div>
              </div>

              <div className="space-y-4">
                 <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 text-sm">
                    <p className="mb-2 font-semibold">Status Koneksi:</p>
                    <div className="flex items-center gap-2">
                       <span className={`w-3 h-3 rounded-full ${dbConfig.isConnected ? 'bg-emerald-500' : 'bg-rose-500'}`}></span>
                       <span className="text-slate-700">{dbConfig.isConnected ? 'Terhubung' : 'Terputus'}</span>
                    </div>
                 </div>

                 {dbMessage && (
                   <div className={`p-3 rounded-lg text-sm flex items-center gap-2 ${dbMessage.type === 'success' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                      {dbMessage.type === 'success' ? <CheckCircle size={16} /> : <XCircle size={16} />}
                      {dbMessage.text}
                   </div>
                 )}

                 <div className="pt-4 flex justify-end">
                    <button 
                      onClick={testDbConnection}
                      disabled={isTestingDB}
                      className="bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white px-6 py-2.5 rounded-lg flex items-center gap-2 transition-colors font-medium"
                    >
                      {isTestingDB ? <RefreshCw size={18} className="animate-spin" /> : <Database size={18} />}
                      Test Koneksi
                    </button>
                 </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Settings;
